In [214]:
import numpy as np

# Given initial state vector (25% for each nucleotide)
initial_state = np.array([0.25, 0.25, 0.25, 0.25])

# Given transition matrix
transition_matrix = np.array(
    [
        [0.83, 0.01, 0.07, 0.06],
        [0.12, 0.94, 0.04, 0.01],
        [0.03, 0.05, 0.79, 0.01],
        [0.02, 0.00, 0.10, 0.92],
    ]
)

### Question 1:
Consider an evenly distributed initial state vector (p = 25%) for each nucleotide and the matrix presented in the description.  Is this setup proper for a Markov Chain?

In [215]:
# Check if cols of the transition matrix sum to 1
col_sums = np.sum(transition_matrix, axis=0)

# Check if all col sums are approximately equal to 1 (within a small tolerance)
is_markov_chain = np.allclose(col_sums, 1)

# Check if the sum of the initial state vector is approximately equal to 1
initial_state_sum = np.sum(initial_state)
is_markov_chain = is_markov_chain and np.isclose(initial_state_sum, 1)

# Output the result
if is_markov_chain:
    print("Yes, the setup forms a Markov Chain.")
else:
    print("No, the setup does not form a Markov Chain.")

print("\nSums of the transition matrix:")
print(col_sums)
print("\nSum of the initial state vector:")
print(initial_state_sum)

Yes, the setup forms a Markov Chain.

Sums of the transition matrix:
[1. 1. 1. 1.]

Sum of the initial state vector:
1.0


### Question 2:
(If there are issues with respect to question 1, fix them).

Which two probability vectors have the smallest dot product?

In [216]:
# Define nucleotide labels
nucleotides = ["A", "C", "G", "T"]

# Calculate the dot product for each pair of probability vectors
dot_products = np.dot(transition_matrix, transition_matrix.T)

# Set diagonal elements to a large value to exclude them from the minimum search
np.fill_diagonal(dot_products, np.inf)

print("\nDot product for each probability vector pair:")
[
    print(f"{nucleotides[i]}/{nucleotides[j]}: {dot_products[i, j]:.3f}")
    for i in range(len(nucleotides))
    for j in range(i + 1, len(nucleotides))
]


Dot product for each probability vector pair:
A/C: 0.112
A/G: 0.081
A/T: 0.079
C/G: 0.082
C/T: 0.016
G/T: 0.089


[None, None, None, None, None, None]

### Question 3:
Assuming that each nucleotide was equally distributed to start, what proportion of nucleotides in one mutation sequence would we expect to be cytosine?  Round to three decimal places and include the leading 0

In [217]:
# Assuming each nucleotide was equally distributed to start
cytosine_proportion = np.dot(
    np.linalg.matrix_power(transition_matrix, 1), initial_state
)[1]
cytosine_proportion_rounded = round(cytosine_proportion, 3)
print(cytosine_proportion_rounded)

0.278


### Question 4:
How many time steps are needed for cytosine to achieve over 40% of the synthetic strand?

In [218]:
# Calculate the number of time steps needed for cytosine to achieve over 40%
cytosine_proportion = 0
time_steps = 0

while cytosine_proportion <= 0.40:
    # Update the state vector with each time step
    initial_state = np.dot(transition_matrix, initial_state)

    # Get the proportion of cytosine
    cytosine_proportion = initial_state[1]

    # Increment the time step
    time_steps += 1

print(time_steps)

9


### Question 5:
Which nucleotide is least likely to occur long term?

In [219]:
# Find the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(transition_matrix)

# Find the index of the eigenvalue 1 (assuming it's the dominant eigenvalue)
index_one = np.where(np.isclose(eigenvalues, 1))[0][0]

# Use the corresponding eigenvector to get the steady-state vector
steady_state_vector = np.real(
    eigenvectors[:, index_one] / np.sum(eigenvectors[:, index_one])
)

# Find the least likely nucleotide
least_likely_nucleotide = nucleotides[np.argmin(steady_state_vector)]

print("\nSteady-State Probabilities:")
for nucleotide, probability in zip(nucleotides, steady_state_vector):
    print(f"{nucleotide}: {probability:.3f}")

print("\nLeast Likely Nucleotide in the Long Term:", least_likely_nucleotide)


Steady-State Probabilities:
A: 0.166
C: 0.466
G: 0.145
T: 0.223

Least Likely Nucleotide in the Long Term: G


### Question 6:
Which nucleotide sees the smallest overall proportion shift after the first time step?

In [220]:
# Calculate and display the proportions for the first 10 time steps
print("\nProportions After Each Time Step:")
for time_step in range(2):
    # Update the state vector with each time step
    initial_state = np.dot(transition_matrix, initial_state)

    # Print the proportions for the current time step
    print(f"Time Step {time_step + 1}:", end=" ")
    for nucleotide, proportion in zip(nucleotides, initial_state):
        print(f"{nucleotide}: {proportion:.4f}", end="   ")
    print()


Proportions After Each Time Step:
Time Step 1: A: 0.1921   C: 0.4079   G: 0.1412   T: 0.2588   
Time Step 2: A: 0.1889   C: 0.4147   G: 0.1403   T: 0.2561   


### Question 7
How many time steps does it take for the second vector norm to get to greater than 0.55?

In [221]:
# re-define the transition matrix
transition_matrix = np.array(
    [
        [0.83, 0.01, 0.07, 0.06],
        [0.12, 0.94, 0.04, 0.01],
        [0.03, 0.05, 0.79, 0.01],
        [0.02, 0.00, 0.10, 0.92],
    ]
)

# re-define the initial state vector
initial_state = np.array([0.25, 0.25, 0.25, 0.25])

# Initialize the time step counter
time_steps = 0

# Print the norm values for each step
print("\nNorm-2 Values After Each Time Step:")
while np.linalg.norm(initial_state, ord=2) <= 0.5505:
    # Print the norm value for the current time step
    print(f"Time Step {time_steps}: {np.linalg.norm(initial_state, ord=2):.4f}")

    # Update the state vector with each time step
    initial_state = np.dot(transition_matrix, initial_state)

    # Increment the time step counter
    time_steps += 1


Norm-2 Values After Each Time Step:
Time Step 0: 0.5000
Time Step 1: 0.5018
Time Step 2: 0.5058
Time Step 3: 0.5107
Time Step 4: 0.5157
Time Step 5: 0.5205
Time Step 6: 0.5250
Time Step 7: 0.5290
Time Step 8: 0.5326
Time Step 9: 0.5358
Time Step 10: 0.5387
Time Step 11: 0.5412
Time Step 12: 0.5435
Time Step 13: 0.5455
Time Step 14: 0.5472
Time Step 15: 0.5488
Time Step 16: 0.5502


### Question 8:
This step is bogus.  Rescale the data using the following (across then down):  (2,1,2,3; 2,2,1,1; 3,3,3,1; 2,1,2,2).  Which column has the largest Norm-Max?

In [222]:
# Redefining the matrix again because not redefining the matrix above was casuing me to return the incorrect values. Once this was redefined the code worked as expected.
# Original matrix
original_data = np.array(
    [
        [0.83, 0.01, 0.07, 0.06],
        [0.12, 0.94, 0.04, 0.01],
        [0.03, 0.05, 0.79, 0.01],
        [0.02, 0.00, 0.10, 0.92],
    ]
)

# Scaling matrix
scaling_matrix = np.array([[2, 1, 2, 3], [2, 2, 1, 1], [3, 3, 3, 1], [2, 1, 2, 2]])

# Rescale the data
rescaled_data = original_data * scaling_matrix

# Calculate the Norm-Max for each column
norm_max_values = np.linalg.norm(rescaled_data, ord=np.inf, axis=0)

# Find the column with the largest Norm-Max
max_norm_column_index = np.argmax(norm_max_values)

print(rescaled_data, "\n")
print("\nNorm-Max Values for Each Rescaled Column:")
print(norm_max_values, "\n")
print(
    max_norm_column_index, "Following zero-index convention, 0 = A, 1 = C, 2 = G, 3 = T"
)

[[1.66 0.01 0.14 0.18]
 [0.24 1.88 0.04 0.01]
 [0.09 0.15 2.37 0.01]
 [0.04 0.   0.2  1.84]] 


Norm-Max Values for Each Rescaled Column:
[1.66 1.88 2.37 1.84] 

2 Following zero-index convention, 0 = A, 1 = C, 2 = G, 3 = T


### Question 9:
What are the four Norm-1 values for the newly rescaled columns?

In [223]:
# Calculate the Norm-1 for each column
norm_1_values = np.linalg.norm(rescaled_data, ord=1, axis=0)

print("\nNorm-1 Values for Each Rescaled Column:")
print(norm_1_values)


Norm-1 Values for Each Rescaled Column:
[2.03 2.04 2.75 2.04]


### Question 10:
Using the answers to Q8 and Q9, rescale the data such that the matrix is fit for a Markov Chain.  Which nucleotide has the lowest
maintenance probability (i.e., diagonal value)?

In [224]:
# Rescale the data to fit a Markov Chain
normalized_rescaled_data = rescaled_data / norm_1_values

# Display the normalized matrix
print("\nNormalized Rescaled Data:")
print(normalized_rescaled_data)

# Find the nucleotide with the lowest maintenance probability
lowest_maintenance_nucleotide = nucleotides[
    np.argmin(np.diag(normalized_rescaled_data))
]
print("\n", lowest_maintenance_nucleotide)


Normalized Rescaled Data:
[[0.81773399 0.00490196 0.05090909 0.08823529]
 [0.1182266  0.92156863 0.01454545 0.00490196]
 [0.04433498 0.07352941 0.86181818 0.00490196]
 [0.01970443 0.         0.07272727 0.90196078]]

 A
